const name = 'BANDORBAN';
const part = name.slice(2,5);
console.log(part);

const  sentance = 'I am a student of class 10 and i am hard workimg';
console.log(sentance.split(""))

const friend = "'aziz', 'asik', 'emon', 'foysal', 'jony', 'deb', 'anik' "
console.log(friend);
console.log(friend.split(","));

const realfrind = ['aziz', 'asik', 'emon', 'foysal', 'jony', 'deb', 'anik'];
console.log(realfrind);
console.log(realfrind.join());
console.log(realfrind.join(""));
console.log(realfrind.join("-"));
console.log(realfrind.join('||'))
console.log(realfrind.join("//"))